### Using an appropriate data set from standard repositories, build the decision tree using ID3 algorithmic technique. Further classify a new sample using the model.

In [1]:
import numpy as pd
import pandas as pd

In [2]:
df = pd.read_csv(r'C:\Users\tuf\Downloads\golf_df.csv')

In [3]:
df.shape

(14, 5)

In [4]:
df.head

<bound method NDFrame.head of      Outlook Temperature Humidity  Windy Play
0      sunny         hot     high  False   no
1      sunny         hot     high   True   no
2   overcast         hot     high  False  yes
3      rainy        mild     high  False  yes
4      rainy        cool   normal  False  yes
5      rainy        cool   normal   True   no
6   overcast        cool   normal   True  yes
7      sunny        mild     high  False   no
8      sunny        cool   normal  False  yes
9      rainy        mild   normal  False  yes
10     sunny        mild   normal   True  yes
11  overcast        mild     high   True  yes
12  overcast         hot   normal  False  yes
13     rainy        mild     high   True   no>

In [5]:
from sklearn.preprocessing import LabelEncoder
l=LabelEncoder()
df.iloc[:,-1]=l.fit_transform(df.iloc[:,-1])
df.iloc[:,-2]=l.fit_transform(df.iloc[:,-2])
df.iloc[:,-3]=l.fit_transform(df.iloc[:,-3])
df.iloc[:,-4]=l.fit_transform(df.iloc[:,-4])
df.iloc[:,-5]=l.fit_transform(df.iloc[:,-5])

In [6]:
features = ['Outlook', 'Temperature', 'Humidity', 'Windy']

In [7]:
X = df[features]

In [8]:
Y = df['Play']

In [9]:
print(X)

    Outlook  Temperature  Humidity  Windy
0         2            1         0      0
1         2            1         0      1
2         0            1         0      0
3         1            2         0      0
4         1            0         1      0
5         1            0         1      1
6         0            0         1      1
7         2            2         0      0
8         2            0         1      0
9         1            2         1      0
10        2            2         1      1
11        0            2         0      1
12        0            1         1      0
13        1            2         0      1


In [10]:
print(Y)

0     0
1     0
2     1
3     1
4     1
5     0
6     1
7     0
8     1
9     1
10    1
11    1
12    1
13    0
Name: Play, dtype: int32


In [11]:
from sklearn.model_selection import train_test_split
X_train, X_test, Y_train, Y_test = train_test_split(X,Y,test_size=0.3)

In [12]:
X_train

Outlook  Temperature  Humidity  Windy
7         2            2         0      0
9         1            2         1      0
1         2            1         0      1
0         2            1         0      0
2         0            1         0      0
11        0            2         0      1
4         1            0         1      0
5         1            0         1      1
13        1            2         0      1

In [13]:
Y_train

7     0
9     1
1     0
0     0
2     1
11    1
4     1
5     0
13    0
Name: Play, dtype: int32

In [14]:
X_test

Outlook  Temperature  Humidity  Windy
10        2            2         1      1
8         2            0         1      0
12        0            1         1      0
3         1            2         0      0
6         0            0         1      1

In [15]:
Y_test

10    1
8     1
12    1
3     1
6     1
Name: Play, dtype: int32

In [16]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier()
dt = dt.fit(X_train,Y_train)

In [17]:
dt

DecisionTreeClassifier()

In [18]:
dt.predict(X_test)

array([0, 0, 1, 1, 1])

In [19]:
Y_pred=dt.predict(X_test)

In [21]:
Y_pred

array([0, 0, 1, 1, 1])

In [22]:
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(Y_pred,Y_test)

In [24]:
print(confusion_matrix)

[[0 2]
 [0 3]]


In [25]:
from sklearn.metrics import accuracy_score
accuracy = accuracy_score(Y_pred,Y_test)*100

In [26]:
print(accuracy)

60.0
